/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemePreviewRouteImport } from './routes/theme-preview'
import { Route as TextRotatePreviewRouteImport } from './routes/text-rotate-preview'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReferenceArticleRouteImport } from './routes/reference-article'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as EditorialPreviewRouteImport } from './routes/editorial-preview'
import { Route as CinematicPreviewRouteImport } from './routes/cinematic-preview'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const ThemePreviewRoute = ThemePreviewRouteImport.update({
  id: '/theme-preview',
  path: '/theme-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const TextRotatePreviewRoute = TextRotatePreviewRouteImport.update({
  id: '/text-rotate-preview',
  path: '/text-rotate-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceArticleRoute = ReferenceArticleRouteImport.update({
  id: '/reference-article',
  path: '/reference-article',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPreviewRoute = EditorialPreviewRouteImport.update({
  id: '/editorial-preview',
  path: '/editorial-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CinematicPreviewRoute = CinematicPreviewRouteImport.update({
  id: '/cinematic-preview',
  path: '/cinematic-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cinematic-preview': typeof CinematicPreviewRoute
  '/editorial-preview': typeof EditorialPreviewRoute
  '/mcp': typeof McpRoute
  '/reference-article': typeof ReferenceArticleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/text-rotate-preview': typeof TextRotatePreviewRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cinematic-preview': typeof CinematicPreviewRoute
  '/editorial-preview': typeof EditorialPreviewRoute
  '/mcp': typeof McpRoute
  '/reference-article': typeof ReferenceArticleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/text-rotate-preview': typeof TextRotatePreviewRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cinematic-preview': typeof CinematicPreviewRoute
  '/editorial-preview': typeof EditorialPreviewRoute
  '/mcp': typeof McpRoute
  '/reference-article': typeof ReferenceArticleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/text-rotate-preview': typeof TextRotatePreviewRoute
  '/theme-preview': typeof ThemePreviewRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cinematic-preview'
    | '/editorial-preview'
    | '/mcp'
    | '/reference-article'
    | '/sitemap.xml'
    | '/text-rotate-preview'
    | '/theme-preview'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cinematic-preview'
    | '/editorial-preview'
    | '/mcp'
    | '/reference-article'
    | '/sitemap.xml'
    | '/text-rotate-preview'
    | '/theme-preview'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/cinematic-preview'
    | '/editorial-preview'
    | '/mcp'
    | '/reference-article'
    | '/sitemap.xml'
    | '/text-rotate-preview'
    | '/theme-preview'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CinematicPreviewRoute: typeof CinematicPreviewRoute
  EditorialPreviewRoute: typeof EditorialPreviewRoute
  McpRoute: typeof McpRoute
  ReferenceArticleRoute: typeof ReferenceArticleRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TextRotatePreviewRoute: typeof TextRotatePreviewRoute
  ThemePreviewRoute: typeof ThemePreviewRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme-preview': {
      id: '/theme-preview'
      path: '/theme-preview'
      fullPath: '/theme-preview'
      preLoaderRoute: typeof ThemePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-rotate-preview': {
      id: '/text-rotate-preview'
      path: '/text-rotate-preview'
      fullPath: '/text-rotate-preview'
      preLoaderRoute: typeof TextRotatePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference-article': {
      id: '/reference-article'
      path: '/reference-article'
      fullPath: '/reference-article'
      preLoaderRoute: typeof ReferenceArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-preview': {
      id: '/editorial-preview'
      path: '/editorial-preview'
      fullPath: '/editorial-preview'
      preLoaderRoute: typeof EditorialPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinematic-preview': {
      id: '/cinematic-preview'
      path: '/cinematic-preview'
      fullPath: '/cinematic-preview'
      preLoaderRoute: typeof CinematicPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CinematicPreviewRoute: CinematicPreviewRoute,
  EditorialPreviewRoute: EditorialPreviewRoute,
  McpRoute: McpRoute,
  ReferenceArticleRoute: ReferenceArticleRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TextRotatePreviewRoute: TextRotatePreviewRoute,
  ThemePreviewRoute: ThemePreviewRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
